version: '3'

services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=rally-results
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
